version: '2.1'

services:
  fact-cron-trigger:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctsprod.azurecr.io/fact/cron-trigger
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
    ports:
      - $SERVER_PORT:$SERVER_PORT
  azure-storage-emulator-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite-blob --blobHost 0.0.0.0 --loose --skipApiVersionCheck
    environment:
      AZURITE_ACCOUNTS: factlocal:cmVmb3Jtc2NhbmtleQo=;
    volumes:
      - ./fact-azure-blob-data:/opt/azurite/folder
    ports:
      - 10000:10000
  init-storage:
    build:
      context: ./docker/storage
    links:
      - azure-storage-emulator-azurite
    depends_on:
      - azure-storage-emulator-azurite
